name: JSON Schema Validator
description: Validate JSON files against specified JSON schema
runs:
  using: docker
  image: Dockerfile
inputs:
  json_schema:
    description: Path to the JSON Schema to validate with
    required: true
  json_path_pattern:
    description: Path to JSON files in RegEx
    required: true
  send_comment:
    description: Create a comment containing validation errors
    required: false
  clear_comments:
    description: Clear previous error comment(s)
    required: false
