on:
  pull_request:
    branches:
      - master
name: Pull request workflow
jobs:
  validate_configurations:
    name: Validate configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate BigQuery schema
        #   uses: ikmals/json-schema-validator
        uses: ./.github/actions/json-schema-validator
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./schemas/bigquery_schema.schema
          json_path_pattern: .*bigquery_schema.json$
          send_comment: true
