on:
  pull_request:
    branches:
      - master
name: Pull request workflow
jobs:
  validate_configurations:
    name: Validate configurations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Validate BigQuery schema
    #   uses: ikmals/json-schema-validator
    #   env:
    #     SCHEMA_DIRECTORY: "./schemas"
    #     JSON_SCHEMA: "bigquery_schema.schema"
    #     JSON_FILE: "bigquery_schema.json"